# This is a config file for access-log-supervisor
# This file defines a set of rules that tell whether an access is allowed, forbidden or suspicious

# If you define a mail address here, any output will be mailed to it
# This requires 'sendmail' is installed and properly configured on this machine
mail: hostmaster@my.host.tld


# (Optional) aliases definitions
# An alias contain a list of (single or multiple):
#   * values (in case it can be parsed as such)
#   * other aliases (otherwise)
addresses:
    lan:
    - 10.0.0.0/8
    - 192.168.0.0/24
    - 192.168.1.0/24
    My home provider:
    - 100.101.102.0/24
    My office provider:
    - 200.201.202.0/16
    My own VPS:
    - 111.222.111.222
    - 2001:2222:2222:b10c::99
    My addresses:
    - lan
    - My home provider
    - My office provider
    - My own VPS

users:
    Me:
    - john
    - John
    - John Lennon
    My friends:
    - paul
    - george
    - ringo

# Note: times are ignored in the current implementation
times:
- Weekends
- Weekdays



# Rules
# The default status is either OK, warning, critical
default_status: critical

# Here are the rules each detected access will be compared against
# The first matching rule will be used. If no rule matches, then the default_rule will apply
# Each rule defines parameters (user, address, etc.)
# Each parameter can be either a "hard-coded" value, an alias, or not defined (in this cas, this acts like a wildcard)
rules:
- {users: Me,   addresses: My addresses, times: Weekdays, status: OK, description: "regular access"}
- {users: root, addresses: 80.81.82.83,  times: Weekdays, status: OK, description: "this rules uses values and aliases"}
- {users: ringo,addresses: 127.0.0.1,    times: Weekends, status: warning, description: "this rules does not use any aliases"}
- {             addresses: 1.2.3.0/29,                    status: warning, description: "I have a specific interest on these addresses"}
